<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-Language" content="en" />

	<title>DataGrid – Nette Framework example</title>

	<!-- custom CSS -->
	<link rel="stylesheet" media="screen" href="{$baseUri}css/cupertino/jquery-ui-1.7.1.custom.css" type="text/css" />
	<link rel="stylesheet" media="screen" href="{$baseUri}css/screen.css" type="text/css" />
	<link rel="stylesheet" media="screen" href="{$baseUri}css/datagrid.css" type="text/css" />
	<link rel="stylesheet" media="screen" href="{$baseUri}css/ajax.css" type="text/css" />
	<link rel="stylesheet" media="screen" href="{$baseUri}css/elements.css" type="text/css" />		
	<link rel="stylesheet" media="print" href="{$baseUri}css/print.css" type="text/css" />
	
	<!-- jQuery -->
	<script src="{$baseUri}js/jquery-1.3.2.min.js" type="text/javascript"></script>
	<script src="{$baseUri}js/jquery-ui-1.6rc6.all.min.js" type="text/javascript"></script>
	<script src="{$baseUri}js/jquery.ui.datepicker-cs.js" type="text/javascript"></script>
	<script src="{$baseUri}js/jquery.corner.js" type="text/javascript"></script>
	
	<!-- custom JS -->
	<script src="{$baseUri}js/jquery.nette.js" type="text/javascript"></script>
	<script src="{$baseUri}js/jquery.nette.forms.js" type="text/javascript"></script>
	<script src="{$baseUri}js/datagrid.js" type="text/javascript"></script>
</head>

<body>
	<h1>DataGrid - Nette Framework example</h1>
	
	{snippet flashMessage}
	<div id="flashes">
		{foreach $flashes as $flash}
		<div class="flash {$flash->type}">{$flash->message}</div>
		{/foreach}
		
		<!-- <div class="flash info">Info message.</div>
		<div class="flash success">Success message.</div>
		<div class="flash warning">Warning message.</div>
		<div class="flash error">Error message.</div>
		<div class="flash validation">Validation message.</div> -->

	</div>
	{/snippet}


	<div id="mainframe-cover">
		<div id="mainframe" class="rounded">
			@{include $content}
		</div>
	</div>
</body>
</html>
