{? Debug::timer('grids-rendering') }


<h2>Example 1 - simple datagrid</h2>
@{? $baseGrid->render()}

<br /><br /><hr /><br /><br />

<h2>Example 2 - simple datagrid with actions and filters</h2>
@{? $officesGrid->render()}

<br /><br /><hr /><br /><br />

<h2>Example 3 - datagrid with actions, filters, operations, paginator and translator (czech locale)</h2>
@{? $customersGrid->render()}

<br />


{? Environment::setVariable('rendering', Debug::timer('grids-rendering') * 1000) }